#URL ung dung
login.url=https://demo4.cybersoft.edu.vn/login
dashboard.url=https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index
# thong tin dang nhap
valid.email=da6368maidinh@gmail.com
valid.password=123456

invalid.email=wronguser
invalid.password=wrongpassword

# cau hinh web driver
brower=chrome
implicit.wait=10

# cau hinh extend report
report.path=test-output
report.name=OrangeHRM Test Output

